### ISSUE TITLE
Update Readme

### ISSUE THREAD

**Issue by MicLamb** [bruno-cadorette/Harambot#1]
Update Readme to be able to understand how to run it. 

List what is required and what are the steps to start using it so I can contribute.

**Comment by bruno-cadorette** [comment]
Hello @MicLamb, I agree that we should update the Readme to be able to understand how to run the app.

However, the contribute steps should be in the CONTRIBUTING.md file, according to the official policy of GitHub. https://help.github.com/articles/setting-guidelines-for-repository-contributors/

**Comment by MicLamb** [comment]
Hi @bruno-cadorette, thanks for sharing the official policy of GitHub.

Would you be able to provide both documents so I could contribute to this awesome project?

**Comment by Dref360** [comment]
I think this is fixed? Please close if that's the case.
